service: get-user-points

provider:
  name: aws
  runtime: nodejs18.x

functions:
  getUserPoints:
    handler: handler.getUserPoints
    events:
      - http:
          path: get-user-points
          method: post

  getUserPointsByLeague:
    handler: handler.getUserPointsByLeague
    events:
      - http:
          path: get-user-points-by-league
          method: post

plugins:
  - serverless-offline
