service: league-ranking

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x

functions:
  getUserPoints:
    handler: handler.getUserPoints
    events:
      - http:
          path: get-user-points
          method: post

  getUserPointsByLeague:
    handler: handler.getUserPointsByLeague
    events:
      - http:
          path: get-user-points-by-league
          method: post

  getUserRankingByBubbleIds:
    handler: handler.getUserRankingByBubbleIds
    timeout: 600
    events:
      - http:
          path: get-user-ranking-by-bubble-ids
          method: post

plugins:
  - serverless-dotenv-plugin
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 3003
